### PR TITLE
Hardcore ender expansion integration.

### PR DESCRIPTION
**Pull request by border999**
It was just confirmed by one of the builders of HEE that they would be fixing the bug of graves being destroyed by their dragon. I am here to say, when the update is released it would be wise to add integration to make sure that the graves are able to register the HEE dragon as an ender dragon. So that the integration will be on both sides.

### CODE REVIEW

**Comment by SinZ163** [comment]
dear god wtf is this pr, 250+ commits

**Comment by fewizz** [comment]
lol :smile:

**Comment by boq** [comment]
I think it was supposed to be issue (continuation of #673), not PR.
Anyway, it looks like it's already fixed, [fully on HEE side](https://github.com/chylex/Hardcore-Ender-Expansion/commit/305df388cc76165e8d5657e8c24a617f20651624), since they just implemented Forge compatibility, that we already supported for quite some time.

**Comment by nevercast** [comment]
Well the comments were a nostalgic read, so it wasn't entirely pointless.

**Pull request closed without merging**
