### PR TITLE
[WIP] IGW-Mod integration

### PR DESCRIPTION
**Pull request by TheSilkMiner**
This Pull Request aims to add to OpenBlocks a full IGW-Mod integration.
The basics are completed, with the addition of a new tab for OpenBlocks and the basic information for blocks and items, taken from the Info-Book.

This is still a WIP, though, because I think that the addition of more information is needed to declare the pages as real wiki-pages.

In particular, the checklist is as follows:
- [X] Add basic integration
- [ ] Substitute all tool-generated warnings with a brief explanation
- [ ] Add some more information
- [ ] Localize all the pages (or should I move it to a different PR?)
- [ ] Implement the changelog page or substitute it
- [ ] Add to OpenModsLib the mod id of IGW-Mod

~~In particular for the last point, should I make a PR to OpenModsLib even if it is a one-line addition?~~
Already added by boq.

@boq I know you already said this was on your TODO list, but I thought that I could "steal" it from you, since mine was (and still is) almost completely empty.

### CODE REVIEW

**Comment by boq** [comment]
Looks ok for now. This task had small priority for me, so it probably would stay on TODO list forever.

I don't like the idea of maintaining two similar sets of item descriptions and I wanted to find some other way to do it, but I guess there is no easy, alternative method, since this extra data can't be encoded in OB book contents.

I will add mod id soon.

Small note about comments: most of the comments can be removed. Please leave ones that are critical. 3 line method with 18 lines of docs looks terrible.

**Comment by TheSilkMiner** [comment]
Before proceeding with the writing of all the others wiki pages, I'd like to know if I can keep the page structure I'm using or if some things should be changed.
The current format is based on the one used by the [Minecraft Wiki (Anvil page)](http://minecraft.gamepedia.com/Anvil).

**Comment by boq** [comment]
That's quite a lot of content for optional feature (and few extra MB to jar). How about moving that to separate mod? I can create one in OpenMods, give you commit rights to that, port existing commits and, once it's released, add to openmods.info. How about that?

Alsom I plan to release soon, and since it's not finished, it would allow releasing that without waiting for other mods.

**Comment by TheSilkMiner** [comment]
I think that another mod is effectively a good idea.
Maybe if IGW Mod is found and an OpenMod is installed without the addon, it could tell the end user.

**Comment by boq** [comment]
Ok, done: OpenMods/OpenMods-IGW. And it comes with build server: https://builds.openmods.info/job/OpenMods-IGW/

I think it should work for all OpenMods with minimal changes.

**Comment by TheSilkMiner** [comment]
Moved to [its own mod](https://github.com/OpenMods/OpenMods-IGW/).

**Pull request closed without merging**
